### ISSUE TITLE
3 Methods not declared in LSDIndexRaster.hpp

### ISSUE THREAD

**Issue by pcfens** [LSDtopotools/LSDTopoTools_ChiMudd2014#1]
The methods
- `LSDIndexRaster LSDIndexRaster::remove_holes_in_patches(int window_radius)`
- `LSDIndexRaster LSDIndexRaster::RemoveSmallPatches(int)`
- `LSDIndexRaster LSDIndexRaster::remove_checkerboard_pattern()`

are implemented in `LSDIndexRaster.cpp`, but not declared in `LSDIndexRaster.hpp`, causing compilation issues. Declaring them in the header file fixes the issue.

**Comment by simon-m-mudd** [comment]
The offending object declaration has been updated.
